#!/bin/bash
#
# This script builds CuraEngine or dm-gcode-generator and runs the tests.
#

set -e
set -x

if [[ $(basename $PWD) != "build" ]]; then
    echo "not in build directory!"
    exit 1
fi


#
# build
#

cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_ARCUS=ON -DBUILD_TESTS:BOOL=ON ..
make -j$(nproc --all)


#
# tests
#

cd ..
./tools/run-tests.sh
