#!/bin/bash
set -e
set -x

PACKAGES="fdm_materials libCharon libSavitar libArcus Uranium CuraEngine Cura"

NPROC=$(nproc --all)

for P in ${PACKAGES}; do
    echo "building: ${P} ${@}"
    pushd "${P}"
    git clean -fdx .
    rm -rf build
    git checkout .
    for V in "${@}"; do
        git checkout "${V}" && break
    done
    mkdir build
    cd build
    cmake .. > out.cmake 2>&1 
    make -j "${NPROC}" > out.build 2>&1
    make install > out.install 2>&1
    popd
done

