#!/bin/bash

export XAUTH_FILE=$(mktemp --tmpdir .Xauthority.pbuilder.XXXXXXXXX)
xauth extract ${XAUTH_FILE} ${DISPLAY}

sudo pbuilder login \
    --basetgz pbuilder-buster-amd64.tgz \
    --configfile $PWD/pbuilderrc \
    --hookdir $PWD/hooks \
    --inputfile ${XAUTH_FILE} \
    --bindmounts "$PWD /tmp/.X11-unix"

rm ${XAUTH_FILE}
