#!/bin/bash
set -x

if [[ ! -x ./CuraEngine ]]; then
    echo "what cura?"
    exit 1
fi

if [[ $(realpath /usr/bin/CuraEngine) != $(realpath ./CuraEngine) ]]; then
    echo "wrong /usr/bin/CuraEngine!"
    echo "it currently points to $(realpath /usr/bin/CuraEngine)"
    echo "run this:"
    echo "sudo rm -f /usr/bin/CuraEngine; sudo ln -s $PWD/CuraEngine /usr/bin"
    exit 1
fi

echo "copying resources to /usr/share/cura/resources..."
TOPLEVEL=$(git rev-parse --show-toplevel)
for R in definitions extruders materials qml quality variants; do
    D="${TOPLEVEL}/resources/${R}"
    if [[ -d "${D}" ]]; then
        sudo /bin/cp -af "${D}" /usr/share/cura/resources/
    fi
done

cura
