#!/bin/bash
#set -x

if [[ ! -x ./CuraEngine ]]; then
    echo "what cura?"
    exit 1
fi

if [[ -d ${PWD}/definitions ]]; then
    export CURA_ENGINE_SEARCH_PATH=${PWD}/definitions:${CURA_ENGINE_SEARCH_PATH}
fi

if [[ -d ${PWD}/extruders ]]; then
    export CURA_ENGINE_SEARCH_PATH=${PWD}/extruders:${CURA_ENGINE_SEARCH_PATH}
fi

if [[ $(realpath /usr/bin/CuraEngine) != $(realpath ./CuraEngine) ]]; then
    echo "wrong /usr/bin/CuraEngine!"
    echo "it currently points to $(realpath /usr/bin/CuraEngine)"
    echo "run this:"
    echo "sudo rm -f /usr/bin/CuraEngine; sudo ln -s $PWD/CuraEngine /usr/bin"
    exit 1
fi

echo "copying resources to /usr/share/cura/resources..."
for R in definitions extruders materials qml quality; do
    if [[ -d ${R} ]]; then
        sudo /bin/cp -af $R /usr/share/cura/resources/
    fi
done

cura
