#!/bin/bash
#set -x

export CURA_ENGINE_SEARCH_PATH=$PWD/definitions:$PWD/extruders:$PWD/printer_presets

if [[ ! -x ./CuraEngine ]]; then
    echo "what cura?"
    exit 1
fi

if [[ $(realpath /usr/bin/CuraEngine) != $(realpath ./CuraEngine) ]]; then
    echo "wrong /usr/bin/CuraEngine!"
    echo "it currently points to $(realpath /usr/bin/CuraEngine)"
    echo "run this:"
    echo "sudo rm -f /usr/bin/CuraEngine; sudo ln -s $PWD/CuraEngine /usr/bin"
    exit 1
fi

echo "copying resources to /usr/share/cura/resources..."
for R in definitions extruders materials qml quality; do
    #printer_presets/
    #gcode_templates/
    sudo /bin/cp -af $R /usr/share/cura/resources/
done

cura
