#!/bin/bash
apt-get install --yes git cmake

apt-get install --yes python3 python3-dev
apt-get install --yes python3-sip python3-sip-dev sip-dev
apt-get install --yes libprotobuf-dev libprotoc-dev protobuf-compiler
#apt-get install --yes doxygen gettext python3-pyqt5
