#!/bin/bash

BUILD_DEPS=(
    git
    cmake

    python3
    python3-dev

    python3-sip
    python3-sip-dev
    sip-dev

    libprotobuf-dev
    libprotoc-dev
    protobuf-compiler

    doxygen
    gettext
)

RUNTIME_DEPS=(
    python3-numpy
)

USER_TOOLS=(
    less
    vim-nox
    screen
)

PACKAGES=(
    ${BUILD_DEPS[*]}
    ${RUNTIME_DEPS[*]}
    ${USER_TOOLS[*]}
)

apt-get install --yes ${PACKAGES[*]}
