#!/bin/bash

BUILD_DEPS=(
    git
    cmake

    python3
    python3-dev

    python3-sip
    python3-sip-dev
    sip-dev

    libprotobuf-dev
    libprotoc-dev
    protobuf-compiler

    doxygen
    gettext
)

RUNTIME_DEPS=(
    python3-numpy
    python3-pyqt5
    python3-pyqt5.qtquick
    python3-serial
    python3-scipy
    python3-shapely
    python3-zeroconf
    libgl1-mesa-dri
    qml-module-qtquick-controls
    qml-module-qtquick-controls2
    qml-module-qtquick-dialogs
    qml-module-qtquick-templates2
)

USER_TOOLS=(
    less
    vim-nox
    screen
)

PACKAGES=(
    ${BUILD_DEPS[*]}
    ${RUNTIME_DEPS[*]}
    ${USER_TOOLS[*]}
)

apt-get install --yes ${PACKAGES[*]}
